import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { ReactNode } from 'react';
import AppClientLayout from "../components/AppClientLayout";
import { LanguageProvider } from '../components/LanguageProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
          <AppClientLayout>{children}</AppClientLayout>
        </LanguageProvider>
      </body>
    </html>
  );
}
