import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "../components/Navbar";
import ClientRoot from "../components/ClientRoot";
import { ReactNode } from 'react';
import { LanguageProvider } from '../components/LanguageProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
          <ClientRoot>
            <Navbar />
            {children}
          </ClientRoot>
        </LanguageProvider>
      </body>
    </html>
  );
}
